# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jerin/Vivado2020/multiplier_mxn_test/multiplier_mxn_test.srcs/sources_1/bd/sys_array/ip/sys_array_axi_gpio_2_0/sys_array_axi_gpio_2_0.xci
# IP: The module: 'sys_array_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jerin/Vivado2020/multiplier_mxn_test/multiplier_mxn_test.gen/sources_1/bd/sys_array/ip/sys_array_axi_gpio_2_0/sys_array_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_array_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jerin/Vivado2020/multiplier_mxn_test/multiplier_mxn_test.gen/sources_1/bd/sys_array/ip/sys_array_axi_gpio_2_0/sys_array_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_array_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jerin/Vivado2020/multiplier_mxn_test/multiplier_mxn_test.gen/sources_1/bd/sys_array/ip/sys_array_axi_gpio_2_0/sys_array_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_array_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Jerin/Vivado2020/multiplier_mxn_test/multiplier_mxn_test.srcs/sources_1/bd/sys_array/ip/sys_array_axi_gpio_2_0/sys_array_axi_gpio_2_0.xci
# IP: The module: 'sys_array_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jerin/Vivado2020/multiplier_mxn_test/multiplier_mxn_test.gen/sources_1/bd/sys_array/ip/sys_array_axi_gpio_2_0/sys_array_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_array_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jerin/Vivado2020/multiplier_mxn_test/multiplier_mxn_test.gen/sources_1/bd/sys_array/ip/sys_array_axi_gpio_2_0/sys_array_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_array_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jerin/Vivado2020/multiplier_mxn_test/multiplier_mxn_test.gen/sources_1/bd/sys_array/ip/sys_array_axi_gpio_2_0/sys_array_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_array_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
