# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z1_c/PYNQ-Z1_C.xdc

# Block Designs: bd/sys_array/sys_array.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array || ORIG_REF_NAME==sys_array} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_processing_system7_0_0/sys_array_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_processing_system7_0_0 || ORIG_REF_NAME==sys_array_processing_system7_0_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_axi_gpio_0_0/sys_array_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_axi_gpio_0_0 || ORIG_REF_NAME==sys_array_axi_gpio_0_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_MbyNMultiplier_0_0/sys_array_MbyNMultiplier_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_MbyNMultiplier_0_0 || ORIG_REF_NAME==sys_array_MbyNMultiplier_0_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_scatter_0_0/sys_array_scatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_scatter_0_0 || ORIG_REF_NAME==sys_array_scatter_0_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_axi_gpio_1_0/sys_array_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_axi_gpio_1_0 || ORIG_REF_NAME==sys_array_axi_gpio_1_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_axi_gpio_1_1/sys_array_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_axi_gpio_1_1 || ORIG_REF_NAME==sys_array_axi_gpio_1_1} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_axi_gpio_2_0/sys_array_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_axi_gpio_2_0 || ORIG_REF_NAME==sys_array_axi_gpio_2_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_axi_gpio_3_0/sys_array_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_axi_gpio_3_0 || ORIG_REF_NAME==sys_array_axi_gpio_3_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_xbar_0/sys_array_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_xbar_0 || ORIG_REF_NAME==sys_array_xbar_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_ps7_0_axi_periph_0/sys_array_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_ps7_0_axi_periph_0 || ORIG_REF_NAME==sys_array_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_rst_ps7_0_50M_0/sys_array_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_rst_ps7_0_50M_0 || ORIG_REF_NAME==sys_array_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_proc_sys_reset_0_0/sys_array_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_proc_sys_reset_0_0 || ORIG_REF_NAME==sys_array_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_clk_wiz_0_0/sys_array_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_clk_wiz_0_0 || ORIG_REF_NAME==sys_array_clk_wiz_0_0} -quiet] -quiet

# IP: bd/sys_array/ip/sys_array_auto_pc_0/sys_array_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_array_auto_pc_0 || ORIG_REF_NAME==sys_array_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Jerin/Vivado2020/multiplier_mxn_test/multiplier_mxn_test.gen/sources_1/bd/sys_array/sys_array_ooc.xdc
